%%%-------------------------------------------------------------------
%%% @doc Property-based tests for erlkoenig_mount_opts.
%%%
%%% Pure functions — the parser and formatter don't touch the outside
%%% world, which makes them perfect PropEr candidates. These tests
%%% generate arbitrary mount-option strings, feed them through the
%%% parser/formatter, and check that invariants hold across every
%%% input rather than a handful of hand-picked cases.
%%%
%%% Covered invariants:
%%%
%%%   1. Round-trip: parse(format(parse(S))) == parse(S). The parser
%%%      and formatter agree on what a "canonical" opts map looks like.
%%%   2. Last-wins: any reordering of the same flag family resolves
%%%      to the last one (e.g. "ro,rw,ro" → ro; "rw,ro,rw" → rw).
%%%   3. Flags are a strict subset of recognised names plus key=value
%%%      passthrough. The parser never invents bits.
%%%   4. Empty / whitespace-only input yields the default opts map.
%%% @end
%%%-------------------------------------------------------------------

-module(erlkoenig_mount_opts_prop_test).

%% PropEr's parse transform routes generator functions through the
%% macros, which the compiler's unused-function check doesn't follow.
%% Suppress the warning rather than hand-export every generator.
-compile(nowarn_unused_function).

-include_lib("proper/include/proper.hrl").
-include_lib("eunit/include/eunit.hrl").

%%--------------------------------------------------------------------
%% Generators
%%--------------------------------------------------------------------

%% A single known flag name. Picked from the same table the parser
%% ships with, so we don't generate bogus tokens that would trip the
%% `unknown_flag` path — that's tested separately below.
known_flag() ->
    oneof([<<"ro">>, <<"rw">>, <<"nosuid">>, <<"suid">>, <<"nodev">>,
           <<"dev">>, <<"noexec">>, <<"exec">>, <<"sync">>, <<"async">>,
           <<"dirsync">>, <<"mand">>, <<"nomand">>, <<"atime">>,
           <<"noatime">>, <<"relatime">>, <<"strictatime">>,
           <<"nodiratime">>, <<"diratime">>, <<"iversion">>,
           <<"noiversion">>, <<"lazytime">>, <<"nolazytime">>,
           <<"nosymfollow">>, <<"bind">>, <<"rbind">>, <<"remount">>,
           <<"silent">>, <<"loud">>]).

%% A propagation mode. These are mutually exclusive — the parser
%% rejects combinations like "private,shared".
propagation_flag() ->
    oneof([<<"private">>, <<"slave">>, <<"shared">>, <<"unbindable">>,
           <<"rprivate">>, <<"rslave">>, <<"rshared">>, <<"runbindable">>]).

%% A key=value passthrough token. The parser accepts these as fs-
%% specific data without semantic interpretation.
data_token() ->
    ?LET({K, V},
         {elements([<<"size">>, <<"mode">>, <<"uid">>, <<"gid">>]),
          integer(1, 10_000)},
         <<K/binary, "=", (integer_to_binary(V))/binary>>).

%% A list of tokens that mixes flags, propagation, and data. Avoids
%% combining two propagation modes (the parser would reject the
%% whole string, which is a different invariant tested below).
flag_list() ->
    ?LET(
        {Flags, MaybeProp, DataTokens},
        {non_empty(list(known_flag())),
         oneof([none, propagation_flag()]),
         list(data_token())},
        %% Order is already effectively random because each sublist
        %% is independently generated; no shuffling needed to get
        %% coverage over flag positions.
        case MaybeProp of
            none -> Flags ++ DataTokens;
            Prop -> Flags ++ [Prop] ++ DataTokens
        end).

%% Produce a comma-separated string from a token list.
opts_string() ->
    ?LET(Tokens, flag_list(), bjoin(<<",">>, Tokens)).

%% Two propagation tokens that are known to conflict (different
%% families). Used to prove the parser rejects them. Generated by
%% picking one family and then a token from a different family —
%% simpler and always-terminating than SUCHTHAT-filtering random
%% pairs.
conflicting_propagation() ->
    ?LET(
        {FamA, FamB},
        ?SUCHTHAT({A, B},
                  {elements([private, slave, shared, unbindable]),
                   elements([private, slave, shared, unbindable])},
                  A =/= B),
        {pick_family_token(FamA), pick_family_token(FamB)}).

pick_family_token(private)    -> oneof([<<"private">>, <<"rprivate">>]);
pick_family_token(slave)      -> oneof([<<"slave">>, <<"rslave">>]);
pick_family_token(shared)     -> oneof([<<"shared">>, <<"rshared">>]);
pick_family_token(unbindable) -> oneof([<<"unbindable">>, <<"runbindable">>]).

%%--------------------------------------------------------------------
%% Properties
%%--------------------------------------------------------------------

%% Property 1: parsing then formatting then re-parsing preserves
%% the mount-fresh semantics of the options. The `clear` bitmask is
%% only meaningful for `MS_REMOUNT` calls; for a fresh mount
%% (flags=0 and no set bits) the formatter deliberately omits
%% inverse tokens like `rw`/`suid`/`exec`, so the exact equality of
%% the full opts map does not hold — but the sub-fields that govern
%% the initial mount semantics do.
%%
%% Found by PropEr on the first run: `parse(<<"rw">>)` returns
%% `flags=0, clear=MS_RDONLY`, but `format/1` emits `""`, which
%% re-parses to `flags=0, clear=0`. That's semantically identical
%% for a fresh bind-mount, so the property asserts only the
%% fresh-mount-equivalent fields.
prop_parse_format_roundtrip() ->
    ?FORALL(
        OptsStr, opts_string(),
        case erlkoenig_mount_opts:parse(OptsStr) of
            {ok, Opts1} ->
                Formatted = erlkoenig_mount_opts:format(Opts1),
                {ok, Opts2} = erlkoenig_mount_opts:parse(Formatted),
                fresh_mount_equiv(Opts1, Opts2);
            {error, _} ->
                %% Any rejection from parse is fine — the property
                %% only asserts the roundtrip when parse succeeds.
                true
        end).

%% Two opts maps describe the same fresh mount if flags, propagation,
%% recursion, and data agree. `clear` is ignored because the formatter
%% drops it (intentionally) on output.
fresh_mount_equiv(A, B) ->
    maps:get(flags, A)       =:= maps:get(flags, B)
    andalso maps:get(propagation, A) =:= maps:get(propagation, B)
    andalso maps:get(recursive, A)   =:= maps:get(recursive, B)
    andalso maps:get(data, A)        =:= maps:get(data, B).

%% Property 2: parsing is idempotent when fed its own formatted form.
%% Tighter than round-trip: one format step is enough; further
%% passes change nothing.
prop_format_idempotent() ->
    ?FORALL(
        OptsStr, opts_string(),
        case erlkoenig_mount_opts:parse(OptsStr) of
            {ok, Opts} ->
                F1 = erlkoenig_mount_opts:format(Opts),
                {ok, Opts2} = erlkoenig_mount_opts:parse(F1),
                F2 = erlkoenig_mount_opts:format(Opts2),
                F1 =:= F2;
            {error, _} -> true
        end).

%% Property 3: last-wins for conflicting simple flags. Take any valid
%% parse, append "ro" or "rw", re-parse, and the RDONLY bit should
%% match the appended token.
prop_last_wins_ro_rw() ->
    ?FORALL(
        {Base, LastFlag}, {opts_string(), elements([<<"ro">>, <<"rw">>])},
        case erlkoenig_mount_opts:parse(<<Base/binary, ",", LastFlag/binary>>) of
            {ok, #{flags := Flags, clear := Clear}} ->
                RdOnly = 16#01,
                case LastFlag of
                    <<"ro">> ->
                        (Flags band RdOnly) =:= RdOnly
                         andalso (Clear band RdOnly) =:= 0;
                    <<"rw">> ->
                        (Flags band RdOnly) =:= 0
                         andalso (Clear band RdOnly) =:= RdOnly
                end;
            {error, _} -> true
        end).

%% Property 4: empty strings and whitespace-only strings always
%% produce the default opts map.
prop_empty_is_default() ->
    Default = erlkoenig_mount_opts:default(),
    ?FORALL(
        Ws, list(elements([$\s, $\t, $,])),
        begin
            {ok, Parsed} = erlkoenig_mount_opts:parse(list_to_binary(Ws)),
            Parsed =:= Default
        end).

%% Property 5: conflicting propagation modes always yield an error,
%% never a silent first-wins or last-wins.
prop_conflicting_propagation_rejected() ->
    ?FORALL(
        {A, B}, conflicting_propagation(),
        case erlkoenig_mount_opts:parse(<<A/binary, ",", B/binary>>) of
            {error, {conflicting_propagation, _, _}} -> true;
            _Other -> false
        end).

%% Property 6: unknown bare tokens always yield an error.
prop_unknown_token_rejected() ->
    ?FORALL(
        Garbage,
        ?SUCHTHAT(
            B,
            ?LET(N, integer(3, 8),
                 list_to_binary([rand_lower_char() || _ <- lists:seq(1, N)])),
            not known_name(B)),
        case erlkoenig_mount_opts:parse(Garbage) of
            {error, {unknown_flag, _}} -> true;
            %% A short string that happens to contain `=` would hit
            %% the data passthrough path, but the SUCHTHAT above
            %% filters out known names — we can still see `=` here
            %% if the random bytes include one. Accept that outcome.
            {ok, _} ->
                binary:match(Garbage, <<"=">>) =/= nomatch
        end).

rand_lower_char() -> $a + rand:uniform(26) - 1.

known_name(B) ->
    lists:member(B,
        [<<"ro">>, <<"rw">>, <<"nosuid">>, <<"suid">>, <<"nodev">>,
         <<"dev">>, <<"noexec">>, <<"exec">>, <<"sync">>, <<"async">>,
         <<"dirsync">>, <<"mand">>, <<"nomand">>, <<"atime">>, <<"noatime">>,
         <<"relatime">>, <<"strictatime">>, <<"nodiratime">>, <<"diratime">>,
         <<"iversion">>, <<"noiversion">>, <<"lazytime">>, <<"nolazytime">>,
         <<"nosymfollow">>, <<"bind">>, <<"rbind">>, <<"remount">>,
         <<"silent">>, <<"loud">>, <<"private">>, <<"slave">>, <<"shared">>,
         <<"unbindable">>, <<"rprivate">>, <<"rslave">>, <<"rshared">>,
         <<"runbindable">>]).

%%--------------------------------------------------------------------
%% eunit wrappers
%%--------------------------------------------------------------------

roundtrip_test() ->
    ?assert(proper:quickcheck(prop_parse_format_roundtrip(),
                              [{numtests, 200}, {to_file, user}])).

format_idempotent_test() ->
    ?assert(proper:quickcheck(prop_format_idempotent(),
                              [{numtests, 200}, {to_file, user}])).

last_wins_test() ->
    ?assert(proper:quickcheck(prop_last_wins_ro_rw(),
                              [{numtests, 200}, {to_file, user}])).

empty_is_default_test() ->
    ?assert(proper:quickcheck(prop_empty_is_default(),
                              [{numtests, 100}, {to_file, user}])).

conflicting_propagation_test() ->
    ?assert(proper:quickcheck(prop_conflicting_propagation_rejected(),
                              [{numtests, 100}, {to_file, user}])).

unknown_token_test() ->
    ?assert(proper:quickcheck(prop_unknown_token_rejected(),
                              [{numtests, 100}, {to_file, user}])).

%%--------------------------------------------------------------------
%% Helpers
%%--------------------------------------------------------------------

bjoin(_Sep, []) -> <<>>;
bjoin(_Sep, [X]) -> X;
bjoin(Sep, [H | T]) ->
    <<H/binary, Sep/binary, (bjoin(Sep, T))/binary>>.

%% Classify a propagation token into its family so the `conflicting`
%% generator only produces genuine conflicts.
prop_family(<<"private">>)    -> private;
prop_family(<<"rprivate">>)   -> private;
prop_family(<<"slave">>)      -> slave;
prop_family(<<"rslave">>)     -> slave;
prop_family(<<"shared">>)     -> shared;
prop_family(<<"rshared">>)    -> shared;
prop_family(<<"unbindable">>) -> unbindable;
prop_family(<<"runbindable">>) -> unbindable.
